-- MySQL Script generated by MySQL Workbench
-- Mon Feb  7 13:38:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drawgallery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `drawgallery` ;

-- -----------------------------------------------------
-- Schema drawgallery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drawgallery` DEFAULT CHARACTER SET utf8 ;
USE `drawgallery` ;

-- -----------------------------------------------------
-- Table `drawgallery`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drawgallery`.`users` ;

CREATE TABLE IF NOT EXISTS `drawgallery`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `surname` VARCHAR(200) NULL,
  `userName` VARCHAR(200) NULL,
  `birthday` DATE NULL,
  `password` VARCHAR(200) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drawgallery`.`Historias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drawgallery`.`Historias` ;

CREATE TABLE IF NOT EXISTS `drawgallery`.`Historias` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `resum` VARCHAR(200) NULL,
  `description` VARCHAR(2000) NOT NULL,
  `mainImg` VARCHAR(100) NOT NULL,
  `otherImg` VARCHAR(100) NULL,
  `country` ENUM('España', 'Europa', 'Otros') NOT NULL,
  PRIMARY KEY (`idpost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drawgallery`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drawgallery`.`Post` ;

CREATE TABLE IF NOT EXISTS `drawgallery`.`Post` (
  `idusers` INT NOT NULL,
  `idPost` INT NOT NULL,
  `pubDate` VARCHAR(45) DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `idusers`
    FOREIGN KEY (`idusers`)
    REFERENCES `drawgallery`.`users` (`idusers`),
  CONSTRAINT `idpost`
    FOREIGN KEY (`idPost`)
    REFERENCES `drawgallery`.`Historias` (`idpost`)
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
